language: elixir
sudo: false
elixir:
  - 1.5
  - 1.4
  - 1.3
otp_release:
  - 20.0
  - 19.3
  - 18.3
matrix:
  exclude:
    - elixir: 1.3
      otp_release: 20.0
notifications:
  email: false
script:
  - mix compile --warnings-as-errors
  - mix credo
  - mix test
