language: elixir
sudo: false
notifications:
  email: false

elixir:
  - 1.6

otp_release:
  - 20.2

script:
  - make testing
after_script:
  - make docs
after_success:
  - bash <(curl -s https://codecov.io/bash)
